apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-vm
  namespace: udn-example
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: test-vm
    spec:
      nodeSelector:
        kubernetes.io/hostname: "ip-10-40-15-65.ap-southeast-4.compute.internal"
      domain:
        cpu:
          cores: 2
        memory:
          guest: 4Gi
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
            - name: secondary
              bridge: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 4Gi
      networks:
        - name: default
          pod: {}
        - name: secondary
          multus:
            networkName: udn-example/aws-eni-network
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: redhat
              chpasswd:
                expire: false
              ssh_pwauth: true
