{{- if .Values.operators.ecrSecret.enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ecr-secret-operator
  namespace: {{ .Values.ecrOperator.namespace }}
spec:
  targetNamespaces:
    - {{ .Values.ecrOperator.namespace }}
    - {{ .Values.tekton.namespace }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ecr-secret-operator
  namespace: {{ .Values.ecrOperator.namespace }}
spec:
  channel: {{ .Values.ecrOperator.channel }}
  name: ecr-secret-operator
  source: {{ .Values.ecrOperator.source }}
  sourceNamespace: {{ .Values.ecrOperator.sourceNamespace }}
  installPlanApproval: Automatic
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-ecr-cloud-credentials
  namespace: {{ .Values.ecrOperator.namespace }}
type: Opaque
stringData:
  credentials: |
    [default]
    role_arn = {{ required "ecrOperator.roleArn is required" .Values.ecrOperator.roleArn }}
    web_identity_token_file = /var/run/secrets/openshift/serviceaccount/token
{{- end }}
