apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.tekton.serviceAccount }}
  namespace: {{ .Values.tekton.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required "tekton.tektonEcrRoleArn is required" .Values.tekton.tektonEcrRoleArn }}
