{{- if and .Values.operators.pipelines.enabled .Values.supplyChain.enabled }}
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rhhi-secure-build
  namespace: {{ .Values.tekton.namespace }}
spec:
  params:
    - name: base-image-url
      type: string
      default: {{ printf "%s/%s/%s" .Values.global.ecrRegistryUrl .Values.global.ecrRepositoryPrefix .Values.images.rhhiBaseImage | quote }}
    - name: destination-image
      type: string
      default: {{ printf "%s/%s" .Values.global.ecrRegistryUrl .Values.images.destinationImage | quote }}
  workspaces:
    - name: source
    - name: dockerconfig
  tasks:
    - name: verify-base-image
      taskRef:
        name: verify-upstream-rhhi
      params:
        - name: base-image-url
          value: $(params.base-image-url)
      workspaces:
        - name: dockerconfig
          workspace: dockerconfig

    - name: ensure-destination-repository
      runAfter: [verify-base-image]
      taskRef:
        name: ensure-ecr-repository
      params:
        - name: destination-image
          value: $(params.destination-image)

    - name: build-and-push
      runAfter: [ensure-destination-repository]
      taskRef:
        name: build-and-push-distroless
      params:
        - name: destination-image
          value: $(params.destination-image)
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig

    - name: sign-image
      runAfter: [build-and-push]
      taskRef:
        name: sign-and-attest-image
      params:
        - name: image-url
          value: $(params.destination-image)
      workspaces:
        - name: dockerconfig
          workspace: dockerconfig
{{- end }}
