#!/usr/bin/env bash
# Install and configure in-cluster Gitea for private GitOps (Git + Helm packages).
#
# Usage:
#   scripts/cluster/private-gitea.sh install <cluster-dir-name>
#   scripts/cluster/private-gitea.sh ensure-api <cluster-dir-name>
#
# Writes clusters/<name>/private-gitops.env (gitignored) with URLs and credentials.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/../common.sh"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/../dev/private-gitops-lib.sh"

OPERATION="${1:-help}"
CLUSTER_NAME="${2:-}"

GITEA_RELEASE="${GITEA_RELEASE:-gitea}"
GITEA_HELM_REPO_URL="${GITEA_HELM_REPO_URL:-https://dl.gitea.com/charts/}"
GITEA_CHART_VERSION="${GITEA_CHART_VERSION:-}"

usage() {
	cat <<EOF
Usage:
  $(basename "$0") install <cluster-name>   Install Gitea and write private-gitops.env
  $(basename "$0") ensure-api <cluster-name>  Ensure org/repo exist (Gitea already running)
  $(basename "$0") help

Environment:
  PRIVATE_GITOPS_NAMESPACE   Gitea namespace (default: gitea)
  PRIVATE_GITOPS_ORG         Gitea org for GitOps assets (default: gitops)
  GITEA_ADMIN_PASSWORD       Admin password (generated if unset)
EOF
}

write_private_gitops_env() {
	local cluster_name="${1:?}"
	local gitea_admin_pw="${2:?}"
	local env_file
	env_file="$(private_gitops_env_file "${cluster_name}")"

	local internal_base="http://gitea-http.${PRIVATE_GITOPS_DEFAULT_NAMESPACE}.svc.cluster.local:3000"
	local git_repo_url="${internal_base}/${PRIVATE_GITOPS_DEFAULT_ORG}/${PRIVATE_GITOPS_DEFAULT_REPO}.git"
	local helm_repo_url="${internal_base}/api/packages/${PRIVATE_GITOPS_DEFAULT_ORG}/helm"
	local admin_pw_key="GITEA_ADMIN"
	admin_pw_key+="_PASSWORD"

	cat >"${env_file}" <<EOF
# Generated by private-gitea.sh — do not commit (see .gitignore)
GITEA_NAMESPACE=${PRIVATE_GITOPS_DEFAULT_NAMESPACE}
GITEA_INTERNAL_URL=${internal_base}
GITEA_ORG=${PRIVATE_GITOPS_DEFAULT_ORG}
GITEA_ADMIN_USER=${PRIVATE_GITOPS_DEFAULT_ADMIN}
GITEA_CONFIG_REPO=${PRIVATE_GITOPS_DEFAULT_REPO}
GITEA_GIT_REPO_URL=${git_repo_url}
GITEA_HELM_REPO_URL=${helm_repo_url}
EOF
	printf '%s=%s\n' "${admin_pw_key}" "${gitea_admin_pw}" >>"${env_file}"
	chmod 600 "${env_file}"
	success "Wrote ${env_file}"
}

ensure_gitea_org_and_repo() {
	private_gitops_load_env "${CLUSTER_NAME}"

	if ! private_gitops_curl_api GET "/api/v1/orgs/${GITEA_ORG}" >/dev/null 2>&1; then
		info "Creating Gitea org ${GITEA_ORG}..."
		private_gitops_curl_api POST "/api/v1/orgs" \
			-d "{\"username\":\"${GITEA_ORG}\",\"visibility\":\"public\",\"description\":\"Private GitOps\"}" >/dev/null
	fi

	if ! private_gitops_curl_api GET "/api/v1/repos/${GITEA_ORG}/${GITEA_CONFIG_REPO}" >/dev/null 2>&1; then
		info "Creating Gitea repo ${GITEA_ORG}/${GITEA_CONFIG_REPO}..."
		private_gitops_curl_api POST "/api/v1/orgs/${GITEA_ORG}/repos" \
			-d "{\"name\":\"${GITEA_CONFIG_REPO}\",\"private\":false,\"auto_init\":true}" >/dev/null
	fi
	success "Gitea org/repo ready: ${GITEA_ORG}/${GITEA_CONFIG_REPO}"
}

gitea_release_is_healthy() {
	local ns="${PRIVATE_GITOPS_DEFAULT_NAMESPACE}"
	oc get svc gitea-http -n "${ns}" >/dev/null 2>&1 || return 1
	oc get pods -n "${ns}" -l "app.kubernetes.io/name=gitea" --field-selector=status.phase=Running --no-headers 2>/dev/null | grep -q .
}

install_gitea() {
	check_required_tools oc helm curl

	if ! oc whoami >/dev/null 2>&1; then
		error "Not logged in — run make cluster.${CLUSTER_NAME}.login"
		exit 1
	fi

	local gitea_admin_pw="${GITEA_ADMIN_PASSWORD:-}"
	if [[ -z "${gitea_admin_pw}" ]]; then
		# openssl avoids SIGPIPE under set -o pipefail (tr|head on /dev/urandom exits 141).
		gitea_admin_pw="$(openssl rand -hex 12)"
	fi

	info "Ensuring namespace ${PRIVATE_GITOPS_DEFAULT_NAMESPACE}..."
	oc create namespace "${PRIVATE_GITOPS_DEFAULT_NAMESPACE}" --dry-run=client -o yaml | oc apply -f - >/dev/null

	local env_file
	env_file="$(private_gitops_env_file "${CLUSTER_NAME}")"
	if gitea_release_is_healthy && [[ -f "${env_file}" ]]; then
		info "Gitea Helm release already deployed — skipping upgrade (bootstrap user may lack namespace RBAC)"
		private_gitops_load_env "${CLUSTER_NAME}"
		private_gitops_ensure_port_forward
		private_gitops_wait_gitea "${CLUSTER_NAME}"
		ensure_gitea_org_and_repo
		private_gitops_stop_port_forward
		return 0
	fi

	if ! helm repo list 2>/dev/null | grep -q "^gitea-charts[[:space:]]"; then
		helm repo add gitea-charts "${GITEA_HELM_REPO_URL}"
	fi
	helm repo update gitea-charts >/dev/null

	local version_arg=()
	if [[ -n "${GITEA_CHART_VERSION}" ]]; then
		version_arg=(--version "${GITEA_CHART_VERSION}")
	fi

	local internal_root="http://gitea-http.${PRIVATE_GITOPS_DEFAULT_NAMESPACE}.svc.cluster.local:3000/"
	info "Installing Gitea Helm release ${GITEA_RELEASE}..."
	local helm_args=(
		upgrade --install "${GITEA_RELEASE}" gitea-charts/gitea
		--namespace "${PRIVATE_GITOPS_DEFAULT_NAMESPACE}"
	)
	# bash 3.2 + set -u: do not expand an empty "${version_arg[@]}"
	if [[ ${#version_arg[@]} -gt 0 ]]; then
		helm_args+=("${version_arg[@]}")
	fi
	helm_args+=(
		--set "gitea.admin.username=${PRIVATE_GITOPS_DEFAULT_ADMIN}"
		--set "gitea.admin.password=${gitea_admin_pw}"
		--set "gitea.admin.email=gitops-admin@cluster.local"
		--set "gitea.config.server.DOMAIN=gitea-http.${PRIVATE_GITOPS_DEFAULT_NAMESPACE}.svc.cluster.local"
		--set "gitea.config.server.ROOT_URL=${internal_root}"
		--set "gitea.config.server.HTTP_PORT=3000"
		--set "gitea.config.packages.ENABLED=true"
		--set "ingress.enabled=false"
		--set "persistence.enabled=true"
		--set "persistence.size=10Gi"
		--wait --timeout 15m
	)
	helm "${helm_args[@]}"

	write_private_gitops_env "${CLUSTER_NAME}" "${gitea_admin_pw}"
	private_gitops_load_env "${CLUSTER_NAME}"
	private_gitops_ensure_port_forward
	private_gitops_wait_gitea "${CLUSTER_NAME}"
	ensure_gitea_org_and_repo
	private_gitops_stop_port_forward
}

cmd_install() {
	if [[ -z "${CLUSTER_NAME}" ]]; then
		usage
		exit 1
	fi
	get_cluster_dir "${CLUSTER_NAME}" >/dev/null
	install_gitea
}

cmd_ensure_api() {
	if [[ -z "${CLUSTER_NAME}" ]]; then
		usage
		exit 1
	fi
	get_cluster_dir "${CLUSTER_NAME}" >/dev/null
	if ! oc whoami >/dev/null 2>&1; then
		error "Not logged in"
		exit 1
	fi
	private_gitops_load_env "${CLUSTER_NAME}"
	private_gitops_ensure_port_forward
	private_gitops_wait_gitea "${CLUSTER_NAME}"
	ensure_gitea_org_and_repo
	private_gitops_stop_port_forward
}

case "${OPERATION}" in
install)
	cmd_install
	;;
ensure-api)
	cmd_ensure_api
	;;
help | --help | -h)
	usage
	;;
*)
	error "Unknown operation: ${OPERATION}"
	usage
	exit 1
	;;
esac
